server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 6
      min-spare: 2
polar:
  greeting: Welcome to the local book catalog!

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
#  cloud:
#    config:
#      uri: http://localhost:8888
#      request-connect-timeout: 5000
#      request-read-timeout: 5000
#      fail-fast: true
#      retry:
#        max-attempts: 6
#        initial-interval: 1000
#        max-interval: 2000
#        multiplier: 1.1
  devtools:
    add-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    username: user
    password: password
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

management:
  endpoints:
    web:
      exposure:
        include: refresh
  endpoint:
    refresh:
      enabled: true
